# Generated by Django 3.2.9 on 2021-12-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_stats_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='user',
            new_name='country',
        ),
    ]
