# Generated by Django 3.2.9 on 2021-12-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_stats_app', '0003_alter_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='LONDON', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='UK', max_length=255, unique=True),
        ),
    ]
