# Generated by Django 3.2.9 on 2021-12-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_stats_app', '0004_auto_20211207_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='date',
            field=models.CharField(default='', max_length=55),
        ),
    ]
